### ISSUE TITLE
planning meeting to discuss possible interop and network-wide scanning tests.

### ISSUE THREAD

**Issue by feamster** [jlivingood/IETF-114-L4S#9]
@jlivingood @gwhiteCL Can we set up a meeting with you to do some pre-planning? 

A student here (@andrewcchu) has already implemented an L4S traceroute. 

We (@andrewcchu and @chasexj) would like to show that to you and get some ideas/opportunities at the hackathon, and scope a project. Seems very worthwhile for us to take advantage of the hardware, etc. that you are bringing to the hackathon.

**Comment by jlivingood** [comment]
@feamster Feel free to join the weekly call Thursdays at 11:30am CT. 

CableLabs Secure Zoom Meeting
https://cablelabs.zoom.us/j/92892593787?pwd=NmlicjNJOXMxY3FERTEzTE5mc1NWQT09&from=addon 
Meeting ID: 928 9259 3787
Password: 873576

CableLabs is hosting this Secure Virtual Meeting for invited participants. See the options below to join this secure meeting.

Zoom Client: For a full-featured and fully encrypted connection, use the above link to join the meeting via your Zoom client.

Browser-Only: Use the link below to "join from your browser" if you do NOT wish to download or utilize the Zoom client.
[https://zoom.us/wc/join/92892593787#](https://zoom.us/wc/join/92892593787) 

Audio-Only Dial-In: Use the available phone numbers. You will be prompted for the meeting ID and password before joining.
One tap mobile
+17209289299,,92892593787#,,#,873576# US (Denver)
+12532158782,,92892593787#,,#,873576# US (Tacoma)

Dial by your location
+1 720 928 9299 US (Denver)
+1 253 215 8782 US (Tacoma)
+1 346 248 7799 US (Houston)
+1 669 900 6833 US (San Jose)
+1 301 715 8592 US (Washington DC)
+1 312 626 6799 US (Chicago)
+1 646 558 8656 US (New York)
+91 22 48 798 004 India
Password: 873576
Find your local number: https://cablelabs.zoom.us/u/ad50PdZmBM 

Join by SIP: Connect via audio-only from an remote conference room system.
92892593787@zoomcrc.com

Join by H.323: Connect via full audio and video from a remote video conference room system.
162.255.37.11 (US West)
162.255.36.11 (US East)
69.174.57.160 (Canada)
Password: 873576

Join by Skype for Business: Use this link to connect. You will need to initially start video in order to be prompted for the meeting password.
https://cablelabs.zoom.us/skype/92892593787

For more information on CableLabs Secure Virtual Meeting go to:
[https://www.cablelabs.com/virtual_meeting](https://urldefense.com/v3/__https:/www.cablelabs.com/virtual_meeting__;!!CQl3mcHX2A!FjxCOS8Ye_AYHhDaK6a6mjiTSGOmjdRYsJh6Gp3zCk00M0uHJVyy0p4FofrbDBt9Tcsld04o2Fb6FMlYq2fNUgro$)
